# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "faq-node"
client_id = "31697786ad6460393ae0ca95fa59c1ac"
application_url = "https://loyal-content-kingfish.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://loyal-content-kingfish.ngrok-free.app/api/auth/tokens",
  "https://loyal-content-kingfish.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "shohan192.myshopify.com"
